import styled from "@emotion/styled";
import Head from "next/head";
import axios from "axios";
import { useCallback, useEffect, useState } from "react";
import Image from "next/image";

type CategoryType =
  | "smartphones"
  | "laptops"
  | "fragrances"
  | "skincare"
  | "groceries"
  | "home-decoration"
  | "furniture"
  | "tops"
  | "womens-dresses"
  | "womens-shoes"
  | "mens-shirts"
  | "mens-shoes"
  | "mens-watches"
  | "womens-watches"
  | "womens-bags"
  | "womens-jewellery"
  | "sunglasses"
  | "automotive"
  | "motorcycle"
  | "lighting";

interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  discountPercentage: number;
  rating: number;
  stock: number;
  brand: string;
  category: CategoryType;
  thumbnail: string;
  images: string[];
}

const Home = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [page, setPage] = useState<number>(1);

  const fetchData = useCallback(async () => {
    const { data } = await axios.get(
      "https://dummyjson.com/products?limit=10&skip=0"
    );

    setProducts(data.products);
  }, []);

  useEffect(() => {
    fetchData();

    return () => {
      setProducts([]);
    };
  }, [fetchData]);

  return (
    <S.Layout>
      <Head>
        <title>Storybook Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Heading>Hello, 안녕</S.Heading>
      <S.Items>
        {products.map((product) => {
          return (
            <S.Item key={product.id}>
              <Image
                src={product.thumbnail}
                alt={product.title + " thumbnail"}
                width={100}
                height={100}
              />
              <span>{product.title}</span>
              <span>{product.description}</span>
              <span>{product.price}</span>
              <span>{product.brand}</span>
              <span>{product.rating}</span>
              <span>{product.stock}</span>
              <span>{product.discountPercentage}</span>
            </S.Item>
          );
        })}
      </S.Items>

      <S.Box>
        <S.Button onClick={() => setPage((prev) => (prev > 1 ? prev - 1 : 1))}>
          {"<"}
        </S.Button>
        <span style={{ padding: "16px" }}>{`[${page}]`}</span>
        <S.Button
          onClick={() => setPage((prev) => (prev < 10 ? prev + 1 : 10))}
        >
          {">"}
        </S.Button>
      </S.Box>
    </S.Layout>
  );
};

export default Home;

const Layout = styled.div`
  width: 100%;
  min-height: 100vh;
  width: 100vw;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Heading = styled.h1`
  font-weight: 900;
  color: #5dd8a5;
  opacity: 0.9;
`;

const Items = styled.ul`
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-columns: repeat(4, 25%);
  grid-template-rows: repeat(3, 1fr);
  row-gap: 8px;
  column-gap: 8px;
`;

const Item = styled.li`
  display: flex;
  flex-direction: column;
  justify-content: center;
  background-color: #f7f7f7;
`;

const Box = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
`;

const Button = styled.button`
  width: 32px;
  background-color: #92b4ec;
  color: #ffffff;
  font-size: 12px;
  font-weight: 700;
`;

const S = {
  Layout,
  Heading,
  Items,
  Item,
  Box,
  Button,
};
