import styled from "@emotion/styled";
import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Storybook Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Hello, 안녕</Heading>
    </div>
  );
};

export default Home;

const Heading = styled.h1`
  font-weight: 900;
  color: #5dd8a5;
  opacity: 0.9;
`;
